/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fedex.smartpost.mts.forms;

import com.fedex.smartpost.mts.services.WindowsRegistryService;
import com.fedex.smartpost.mts.tools.ScanDashboard;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 796812
 */
public class MainUI extends JFrame {
	private static final long serialVersionUID = -5768417181099665250L;
	private ResetEventsUI resetEventsUI;
	private UnreleaseUI unreleaseUI;
	private CredentialUI credentialUI;
	private SetAutogroupingUI setAutogroupingUI;

	/**
	 * Creates new form MainUI
	 */
	public MainUI() {
		initComponents();
		setLocation(WindowsRegistryService.getWindowLocation());
	}

	private void buildCredentials() {
		if (credentialUI == null) {
			credentialUI = new CredentialUI(this);
		}
		credentialUI.setVisible(true);
		setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblTitle = new javax.swing.JLabel();
        lblTool = new javax.swing.JLabel();
        cbxTool = new javax.swing.JComboBox<>();
        btnOpen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        mnuCredentials = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Michael's Tool Suite");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Michael's Tool Suite");

        lblTool.setText("Tool:");

        cbxTool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reset Events", "Unrelease BGs", "Scan Dashboard", "Set Autogrouping" }));

        btnOpen.setText("OpenTool");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jMenu.setText("Settings");

        mnuCredentials.setText("Credentials");
        mnuCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCredentialsActionPerformed(evt);
            }
        });
        jMenu.add(mnuCredentials);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTool)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTool, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOpen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTool)
                    .addComponent(cbxTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
		if (!WindowsRegistryService.credentialsSet()) {
			buildCredentials();
		}
		switch (cbxTool.getSelectedIndex()) {
			case 0:
				if (resetEventsUI == null) {
					resetEventsUI = new ResetEventsUI(this);
				}
				resetEventsUI.setVisible(true);
				setVisible(false);
				break;
			case 1:
				if (unreleaseUI == null) {
					unreleaseUI = new UnreleaseUI(this);
				}
				unreleaseUI.setVisible(true);
				setVisible(false);
				break;
			case 2:
				try {
					ScanDashboard dashboard = new ScanDashboard();
					btnOpen.setEnabled(false);
					cbxTool.setEnabled(false);
					dashboard.process();
				}
				catch (Exception e) {
					JOptionPane.showMessageDialog(this, e.getMessage(), "Exception Caught", JOptionPane.ERROR_MESSAGE);
				}
				finally {
					btnOpen.setEnabled(true);
					cbxTool.setEnabled(true);
				}
			case 3:
				if (setAutogroupingUI == null) {
					setAutogroupingUI = new SetAutogroupingUI(this);
				}
				setAutogroupingUI.setVisible(true);
				setVisible(false);
				break;
		}
    }//GEN-LAST:event_btnOpenActionPerformed

    private void mnuCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCredentialsActionPerformed
		buildCredentials();
    }//GEN-LAST:event_mnuCredentialsActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
		WindowsRegistryService.setWindowLocation(getLocation());
    }//GEN-LAST:event_formComponentMoved

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainUI().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JComboBox<String> cbxTool;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTool;
    private javax.swing.JMenuItem mnuCredentials;
    // End of variables declaration//GEN-END:variables
}
