CREATE VOLATILE TABLE CONTAINER_MG AS
(
      WITH RECURSIVE CONTAINER (CNTNR_NM,TRGT_CNTNR_NBR) AS
      (
            SELECT CNTNR_NM, TRGT_CNTNR_NBR
            FROM SMARTPOST_EDS_PROD_VIEW_DB.FXSP_CONTAINER
            WHERE CNTNR_NM IN (SELECT CNTNR_NM FROM CONTAINER_MV)
            AND CNTNR_EVENT_TYPE_CD ='CNTMG'
            
            UNION ALL
            
            SELECT CNT.CNTNR_NM,CNTMG.TRGT_CNTNR_NBR
            FROM CONTAINER AS CNT, SMARTPOST_EDS_PROD_VIEW_DB.FXSP_CONTAINER AS CNTMG
            WHERE CNT.TRGT_CNTNR_NBR = CNTMG.CNTNR_NM
            AND CNTMG.CNTNR_EVENT_TYPE_CD ='CNTMG'
      )
      
      SELECT * FROM CONTAINER 
) WITH DATA ON COMMIT PRESERVE ROWS

